---
title: "Job Satisfaction: Mixed Effects Ordinal Regression"
author: "Marina Wyss & Daisy Pacheco"
date: "12/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GLMMadaptive)
library(car)
library(lattice)

set.seed(123)

# load and filter data
load("data/full_prepped_data.RData")

prepped_data$job_satisfaction = as.factor(prepped_data$job_satisfaction)

# filtering for full time
full_time_data <- prepped_data %>% 
  filter(hours_worked_week >= 35) %>% 
  select(-full_time)

# filtering for public sector
public_data <- full_time_data %>% 
  filter(public == 1) %>% 
  select(-public)

private_data <- full_time_data %>% 
  filter(public == 0) %>% 
  select(-public)
```

## Linear Model Assumptions Checks

```{r}
model_vif <- glm(job_satisfaction ~
                   religion + 
                   ethnicity + 
                   gender + 
                   highest_grade + 
                   urban_rural +
                   net_family_income_centered +
                   job_number + 
                   union + 
                   hourly_pay_centered + 
                   rotter_score_centered + 
                   rosenberg_score_centered +
                   public + 
                   avg_age_per_job_centered + 
                   tenure_centered,
                 data = full_time_data,
                 family = binomial())

summary(model_vif)

vif_values <- vif(model_vif)

res <- resid(model_vif)

plot(fitted(model_vif), res)
```


## Mixed-Effects Ordinal Regression Models

### Full Model

```{r}
full_glmm_interact <- mixed_model(job_satisfaction ~
                                    religion + 
                                    ethnicity + 
                                    gender + 
                                    highest_grade + 
                                    urban_rural +
                                    net_family_income_centered +
                                    job_number + 
                                    union + 
                                    hourly_pay_centered + 
                                    rotter_score_centered + 
                                    rosenberg_score_centered +
                                    public + 
                                    avg_age_per_job_centered + 
                                    tenure_centered + 
                                    public * avg_age_per_job_centered + 
                                    public * tenure_centered,
                                  random = ~ 1 | id, 
                                  data = full_time_data,
                                  family = binomial())

summary(full_glmm_interact)
```

### Public Sector Ony

```{r}
public_glmm <- mixed_model(job_satisfaction ~
                             religion + 
                             ethnicity + 
                             gender + 
                             highest_grade + 
                             urban_rural + 
                             net_family_income_centered +
                             job_number + 
                             union + 
                             hourly_pay_centered + 
                             rotter_score_centered + 
                             rosenberg_score_centered +
                             avg_age_per_job_centered + 
                             tenure_centered,
                           random = ~ 1 | id, 
                           data = public_data,
                           family = binomial())

summary(public_glmm)
```

### Private Sector Ony

Note that for some reason this momdel has a very large (though no significant) coef for folks with "other" highest level of education.

```{r}
private_glmm <- mixed_model(job_satisfaction ~
                              religion + 
                              ethnicity + 
                              gender + 
                              highest_grade + 
                              urban_rural +
                              net_family_income_centered +
                              job_number + 
                              union + 
                              hourly_pay_centered + 
                              rotter_score_centered + 
                              rosenberg_score_centered +
                              avg_age_per_job_centered + 
                              tenure_centered,
                            random = ~ 1 | id, 
                            data = private_data,
                            family = binomial(),
                            max_coef_value = 15)

summary(private_glmm)
```

